favicon = "images/favicon.png"
logo = "images/logo.svg"
logo_darkmode = "images/logo-darkmode.svg"
logo_width = "160px"
logo_height = "64px"
logo_webp = true
logo_text = "Nikolai Razouvaev"
theme_switcher = true
theme_default = "light" # available options [light/dark/system]
mainSections = ["blog"]
form_processor = "netlify"
form_action = "/thank-you/"
# google_tag_manager = ""
# google_adsense = ""
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
copyright = "&copy; 2014-{year} Nikolai Razouvaev"

[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

[navigation_button]
enable = true
label = "contact me"
link = "contact"

[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

[announcement]
enable = false
expire_days = 7
content = ""

# meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Road Cycling", "Blog"]
description = "Nikolai Razouvaev's personal blog."
author = "Nikolai Razouvaev"
# twitter = "nik"
# image = "images/og-image.png"

# [site_verification]
# google = ""

# [cookies]
# enable = false
# expire_days = 60
# content = "This site uses cookies. By continuing to use this website, you agree to their use."
# button = "I Accept"

# diagrams
[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

[widgets]
sidebar = ["categories", "tags"]

# [google_map]
# enable = false
# map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png"

[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
